sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t bryanesmith/complex-docker-client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bryanesmith/complex-docker-client-dev npm test

after_success:
  - docker build -t bryanesmith/complex-docker-client ./client
  - docker build -t bryanesmith/complex-docker-nginx ./nginx
  - docker build -t bryanesmith/complex-docker-server ./server
  - docker build -t bryanesmith/complex-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bryanesmith/complex-docker-client
  - docker push bryanesmith/complex-docker-nginx
  - docker push bryanesmith/complex-docker-server
  - docker push bryanesmith/complex-docker-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'complex-docker'
  env: 'Complex-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-891377378855'
  bucket_path: 'complex-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY