sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t bryanesmith/complex-client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bryanesmith/complex-client-dev npm test

after_success:
  - docker build -t bryanesmith/complex-client ./client
  - docker build -t bryanesmith/complex-nginx ./nginx
  - docker build -t bryanesmith/complex-server ./server
  - docker build -t bryanesmith/complex-worker ./worker