sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t bryanesmith/complex-docker-client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bryanesmith/complex-docker-client-dev npm test

after_success:
  - docker build -t bryanesmith/complex-docker-client ./client
  - docker build -t bryanesmith/complex-docker-nginx ./nginx
  - docker build -t bryanesmith/complex-docker-server ./server
  - docker build -t bryanesmith/complex-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bryanesmith/complex-docker-client
  - docker push bryanesmith/complex-docker-nginx
  - docker push bryanesmith/complex-docker-server
  - docker push bryanesmith/complex-docker-worker